---
  # YOU NEED TO GATHER FACTS HERE
  # If you don't, the connection will not work.
  - name: Gather facts
    icx_facts:
      gather_subset: all


        #  - name: Configure users
        #    icx_user:
        #      aggregate: "{{ icx_users }}"
        #      purge: "yes"

  - name: System config
    community.network.icx_system:
      hostname: "{{ inventory_hostname }}"
      domain_name: "{{ polynet_core_domain_name }}"

  - name: General setup
    icx_config:
      lines:
        - enable acl-per-port-per-vlan
        - aaa authentication web-server default local
        - aaa authentication enable default local
        - aaa authentication enable implicit-user
        - aaa authentication login default local
        - aaa authentication login privilege-mode
        - jumbo
        - enable aaa console
        - logging console
        - no telnet server
        - ip multicast active
        - ip multicast leave-wait-time 4
        - clock summer-time
        - web-management https
        - spanning-tree
        - ip load-sharing 8
        - logging host {{ syslog_host }}
        - optical-monitor 15
        - ip dhcp-client disable
        - ipv6 unicast-routing
        - router vrrp
        - ipv6 router vrrp
        - snmp-server community public ro
        - system-max spanning-tree 96
        - lldp enable ports all
        - lldp run

  - name: Turn on OSPF
    icx_config:
      parents: "router ospf"
      lines:
        - area 0.0.0.0
        - log all

  - name: Turn on OSPF3
    icx_config:
      parents: "ipv6 router ospf"
      lines:
        - area 0.0.0.0
        #- log all

  - name: Setup core VLANs
    icx_vlan:
      vlan_id: "{{ item.value.number }}"
      name: "{{ item.value.description }}"
      stp:
        enabled: true
      tagged:
        name:
          - ethernet 1/1/1 to 1/1/48
    with_dict: "{{ global_vlans }}"

  - name: Setup cross-switch LAG
    icx_linkagg:
      name: px1
      group: 1
      mode: dynamic
      members:
        - ethernet 1/2/1 to 1/2/2

  - name: Setup upstream LAG
    icx_linkagg:
      name: px2
      group: 2
      mode: dynamic
      members:
        - ethernet 1/1/55 to 1/1/56

  - name: Setup cross-switch vlan
    icx_vlan:
      vlan_id: "4093"
      name: "sync"
      stp:
        enabled: true
      tagged:
        name:
          - ethernet 1/2/1 to 1/2/2

  - name: Setup upstream vlan
    icx_vlan:
      vlan_id: "199"
      name: "eth"
      stp:
        enabled: false
      interfaces:
        name:
          - ethernet 1/1/55 to 1/1/56

  - name: Enable routing on cross-switch vlan
    icx_config:
      parents: "vlan 4093"
      lines:
        - router-interface ve 4093

  - name: Enable routing on upstream vlan
    icx_config:
      parents: "vlan 199"
      lines:
        - router-interface ve 199

  - name: Setup cross-switch vlan IP
    icx_config:
      parents: "interface ve 4093"
      lines:
        - ip address {{ polynet_core_config[inventory_hostname].ip }} 255.255.255.0
        - ipv6 address {{ polynet_core_config[inventory_hostname].ip6 }}/120
        - ip ospf area 0.0.0.0
        - ipv6 ospf area 0.0.0.0
        - spanning-tree

  - name: Setup upstream vlan IP
    icx_config:
      parents: "interface ve 199"
      lines:
        - ip address {{ polynet_core_config[inventory_hostname].upstream_ip }} 255.255.255.0
        - ipv6 address {{ polynet_core_config[inventory_hostname].upstream_ip6 }}/120
        - ip ospf area 0.0.0.0
        - ipv6 ospf area 0.0.0.0
        - no spanning-tree

  - name: Setup shared VLANs
    with_items: "{{ polynet_core_provided_vlans }}"
    icx_vlan:
      vlan_id: "{{ item.vlan }}"
      name: "{{ item.name }}"
      stp:
        # Do not enable STP on the upstream vlan
        enabled: "{{ item.vlan != 199 }}"
        priority: "{{ 10 if item.switchconf[inventory_hostname].role == 'owner' else 20 }}"
      tagged:
        name:
          - ethernet {{ item.port }}
          - ethernet 1/2/1 to 1/2/2

  - name: Enable routing on shared vlans
    with_items: "{{ polynet_core_provided_vlans }}"
    icx_config:
      parents: "vlan {{ item.vlan }} name {{ item.name }} by port"
      lines:
        - router-interface ve {{ item.vlan }}

  - name: Setup shared VLAN interfaces
    with_items: "{{ polynet_core_provided_vlans }}"
    icx_config:
      parents: "interface ve {{ item.vlan }}"
      lines:
       - ip address {{ item.switchconf[inventory_hostname].ip }} {{ item.netmask|default('255.255.255.0') }}
       - ipv6 address {{ item.switchconf[inventory_hostname].ip6 }}/120
       - ip helper-address 1 {{ polynet_core_dhcp_helper_a }}
       - ip helper-address 2 {{ polynet_core_dhcp_helper_b }}
       - ip ospf area 0.0.0.0
       - ipv6 ospf area 0.0.0.0
       - ip vrrp vrid {{ item.vrrp }}

  - name: Setup shared vlans vrrp (v4, backup)
    with_items: "{{ polynet_core_provided_vlans }}"
    when: item.switchconf[inventory_hostname].role == "backup"
    icx_config:
      parents:
        - "interface ve {{ item.vlan }}"
        - "ip vrrp vrid {{ item.vrrp }}"
      lines:
        - "{{ item.switchconf[inventory_hostname].role }}"
        - version v3
        - accept-mode
        - advertise backup
    tags:
      - vrrp

  - name: Setup shared vlans vrrp (v4)
    with_items: "{{ polynet_core_provided_vlans }}"
    icx_config:
      parents:
        - "interface ve {{ item.vlan }}"
        - "ip vrrp vrid {{ item.vrrp }}"
      lines:
        - "{{ item.switchconf[inventory_hostname].role }}"
        - version v3
        - ip-address {{ item.haip }}
        - activate
    tags:
      - vrrp

  - name: Setup shared vlans vrrp (v6, backup)
    with_items: "{{ polynet_core_provided_vlans }}"
    when: item.switchconf[inventory_hostname].role == "backup"
    icx_config:
      parents:
        - "interface ve {{ item.vlan }}"
        - "ipv6 vrrp vrid {{ item.vrrp }}"
      lines:
        - "{{ item.switchconf[inventory_hostname].role }}"
        - accept-mode
        - advertise backup
    tags:
      - vrrp
      - vrrp6

  - name: Setup shared vlans vrrp (v6)
    with_items: "{{ polynet_core_provided_vlans }}"
    icx_config:
      parents:
        - "interface ve {{ item.vlan }}"
        - "ipv6 vrrp vrid {{ item.vrrp }}"
      lines:
        - "{{ item.switchconf[inventory_hostname].role }}"
        - ipv6-address {{ item.haip6 }}
        - activate
    tags:
      - vrrp
      - vrrp6