---
  - name: Gather facts
    icx_facts:
      gather_subset: all



        #  - name: Configure users
        #    icx_user:
        #      aggregate: "{{ icx_users }}"
        #      purge: "yes"

  - name: System config
    icx_system:
      hostname: "{{ inventory_hostname }}"
      domain_name: "{{ polynet_core_domain_name }}"

  - name: General setup
    icx_config:
      lines:
        - enable acl-per-port-per-vlan
        - aaa authentication web-server default local
        - aaa authentication enable default local
        - aaa authentication enable implicit-user
        - aaa authentication login default local
        - aaa authentication login privilege-mode
        - jumbo
        - enable aaa console
        - logging console
        - no telnet server
        - ip multicast active
        - ip multicast leave-wait-time 4
        - clock summer-time
        - web-management https
        - spanning-tree

  - name: Setup core VLANs
    icx_vlan:
      vlan_id: "{{ item.value.number }}"
      name: "{{ item.value.description }}"
      stp:
        enabled: true
        priority: 65530
      tagged:
        name:
          - ethernet 1/1/1 to 1/1/23
    with_dict: "{{ global_vlans }}"
