---
  - name: Gather facts
    icx_facts:
      gather_subset: all



        #  - name: Configure users
        #    icx_user:
        #      aggregate: "{{ icx_users }}"
        #      purge: "yes"

  - name: System config
    icx_system:
      hostname: "{{ inventory_hostname }}"
      domain_name: "{{ polynet_core_domain_name }}"

  - name: General setup
    icx_config:
      lines:
        - enable acl-per-port-per-vlan
        - aaa authentication web-server default local
        - aaa authentication enable default local
        - aaa authentication enable implicit-user
        - aaa authentication login default local
        - aaa authentication login privilege-mode
        - jumbo
        - enable aaa console
        - logging console
        - no telnet server
        - ip multicast active
        - ip multicast leave-wait-time 4
        - clock summer-time
        - web-management https
        - spanning-tree

  - name: Setup core VLANs
    icx_vlan:
      vlan_id: "{{ item.value.number }}"
      name: "{{ item.value.description }}"
      stp:
        enabled: true
        priority: 65530
      tagged:
        name:
          - ethernet 1/1/1 to 1/1/23
    with_dict: "{{ global_vlans }}"

  - name: Setup LAG 
    icx_linkagg:
      name: px1
      group: 1
      mode: dynamic
      members:
        - ethernet 1/1/23 to 1/1/24

  - name: Setup shared VLANs
    with_items: "{{ polynet_core_provided_vlans }}"
    icx_vlan:
      vlan_id: "{{ item.vlan }}"
      name: "{{ item.name }}"
      stp:
        enabled: true
        priority: 65530
      tagged:
        name:
          - ethernet 1/1/1 to 1/1/23

  - name: Enable routing on shared vlans
    with_items: "{{ polynet_core_provided_vlans }}"
    icx_config:
      parents: "vlan {{ item.vlan }} name {{ item.name }} by port"
      lines:
        - router-interface ve {{ item.vlan }

  - name: Setup shared VLAN interfaces
    with_items: "{{ polynet_core_provided_vlans }}"
    icx_config:
      parents: "interface ve {{ item.vlan }}"
      lines:
        ip address 10.233.64.2 255.255.255.0
        ip helper-address 1 {{ polynet_core_dhcp_helper_a }}
        ip helper-address 2 {{ polynet_core_dhcp_helper_b }}
        ip ospf area 0.0.0.0
        ip vrrp vrid {{ item.vrrp }}

  - name: Setup shared vlans vrrp
    with_items: "{{ polynet_core_provided_vlans }}"
    icx_config:
      parents:
        - "interface ve {{ item.vlan }}"
        - "ip vrrp vrid {{ item.vrrp }}"
      lines:
        - "{{ item.switchconf[inventory_hostname].role }}"
        - ip-address "{{ item.switchconf[inventory_hostname].role }}"
        - activate
